### ISSUE TITLE
Third party library (Emojione) lacks explicit License

### ISSUE THREAD

**Issue by Nathan-Smith** [StreetHawkSDK/ios#2]
Emojione should be replaced with another Emoji mapping library that contains a proper open source license (e.g. GPL, LGPL, MIT, etc).

**Comment by ChristineXYS** [comment]
Hi Nathan, 

Thanks for your feedback. The emoji has been handled by StreetHawk server well, and client side does not need the third-party component. I have removed it from iOS SDK in latest release 1.8.5, please sync. 

You can setup emoji in StreetHawk web when creating campaign:
![emoji](https://cloud.githubusercontent.com/assets/1209478/18857734/f201b0d8-8498-11e6-9f11-b1c6d1b61a6b.png)

Thanks & regards, 
Christine

**Comment by Nathan-Smith** [comment]
@ChristineXYS thanks
You may want to update the podspec since it still references Emojione (https://github.com/StreetHawkSDK/ios/blob/master/streethawk.podspec#L51)

**Comment by ChristineXYS** [comment]
Good point. I fixed it.
