### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by eduardo22i** [StreetHawkSDK/ios#4]
They binary SDK provided on your website (https://bitbucket.org/shawk/streethawk-ios-sdk/downloads), contains several warnings :

warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/9377QYN7MEQL/UIKit-1L3UEFDVKSNO6.pcm: No such file or directory

warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/9377QYN7MEQL/CoreTelephony-2EM9NI7WGGCMS.pcm: No such file or directory
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/9377QYN7MEQL/CoreLocation-3TVN350RTA92B.pcm: No such file or directory

warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/9377QYN7MEQL/MessageUI-3M6PWJ45T0NZQ.pcm: No such file or directory

Thanks,
Eduardo

**Comment by ChristineXYS** [comment]
Hi, 

Thank you for your feedback. A new version 1.8.5 is updated. Would you please try again? If you still meet the warning message, would you please share me some more information as I cannot reproduce the issue here? If a simple project can show the warning, that would be great help!

I close the ticket so far. If the new SDK 1.8.5 still have warning, please feel free to open it again. 

Thanks & regards, 
Christine

**Comment by eduardo22i** [comment]
I'm still getting the issue. 

while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/MobileCoreServices-N94D31PLFESQ.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/Security-27ZMYP8CODFT0.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHUtils.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/CoreTelephony-E0K26IE3JFHL.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHBeaconStatus.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/CoreLocation-2RB9TGORWT0YQ.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHInteractiveButtons.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/UserNotifications-N94D31PLFESQ.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHGrowth.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/MessageUI-N94D31PLFESQ.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHGrowth.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/Social-3EHAQSWIIEC28.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHCoverWindow.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/1E27OMMCSJPMF/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHCoverWindow.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/1E27OMMCSJPMF/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHApp.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/CoreSpotlight-AUU12EFPKK1S.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHMBProgressHUD.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHLocationManager.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/3ONYDAIB2Y2H0/CoreBluetooth-14O21S15A37HY.pcm: No such file or directory
while processing /Users/eduardoirias/Developer/apptuto-ios/Frameworks/StreetHawkCore.framework/StreetHawkCore(SHPresentDialog.o):
warning: /var/folders/0v/3q73vb7j5lxb9rjdvnrsshh80000gn/C/org.llvm.clang.christine/ModuleCache/1E27OMMCSJPMF/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory

<img width="947" alt="screen shot 2016-11-21 at 4 57 16 pm" src="https://cloud.githubusercontent.com/assets/406251/20504138/989cfc52-b00b-11e6-9f47-9bce7a444505.png">

**Comment by ChristineXYS** [comment]
Thanks for this time's detail information. The warning prints a very important message:

**note: Linking a static library that was built with -gmodules, but the module cache was not found. Redistributable static libraries should never be built with module debugging enabled. The debug experience will be degraded due to incomplete debug information.**

And this leads me to the right direction. 

By investigation, I can reproduce the issue now. The key is: you need to "Archive" instead of simple "Run". (https://github.com/realm/realm-cocoa/issues/4205)

**Comment by ChristineXYS** [comment]
The setting to fix this warning. http://stackoverflow.com/questions/36265490/turning-off-clang-enable-module-debugging-consequences. 

Do local test here and no warnings any more.

**Comment by ChristineXYS** [comment]
Fixed in release 1.8.6.

**Comment by eduardo22i** [comment]
Great!!!!! Thanks! ;)
