### ISSUE TITLE
README and Podspec minimum iOS version inconsistent

### ISSUE THREAD

**Issue by Nathan-Smith** [StreetHawkSDK/ios#5]
See https://github.com/StreetHawkSDK/ios/blame/master/README.md#L7 and https://github.com/StreetHawkSDK/ios/blob/master/streethawk.podspec#L20

Changing the minimum iOS version in a patch version (1.8.5) should also be considered a breaking change. Is this SDK following [Semantic Versioning](semver.org)?

**Comment by ChristineXYS** [comment]
Thank you Nathan. I correct the version number in readme.
