### ISSUE TITLE
StreetHawk is Crashing

### ISSUE THREAD

**Issue by eduardo22i** [StreetHawkSDK/ios#6]
We are using Crashlytics to detect our app crashes and we have detected 3 crashes related to StreetHawk Framework:

SHAFURLRequestSerialization.m line 315
-[SHAFHTTPRequestSerializer setValue:forHTTPHeaderField:]

SHAFURLRequestSerialization.m line 547
-[SHAFHTTPRequestSerializer observeValueForKeyPath:ofObject:change:context:]

SHAFURLRequestSerialization.m line 309
-[SHAFHTTPRequestSerializer HTTPRequestHeaders]

**Comment by ChristineXYS** [comment]
Thanks for the feedback. Would you please share more information, for example:
- is there any exception message collected by Crashlytics?
- does Crashlytics symbolicate the crash report file?
- what's iOS version?

Thanks & regards, 
Christine

**Comment by eduardo22i** [comment]
<img width="1062" alt="screen shot 2016-11-21 at 4 59 14 pm" src="https://cloud.githubusercontent.com/assets/406251/20504191/dd23dd82-b00b-11e6-9763-a89afdd35c08.png">

<img width="1011" alt="screen shot 2016-11-21 at 4 58 53 pm" src="https://cloud.githubusercontent.com/assets/406251/20504181/d12a0cb8-b00b-11e6-990c-1edea7301bce.png">

<img width="1055" alt="screen shot 2016-11-21 at 4 59 46 pm" src="https://cloud.githubusercontent.com/assets/406251/20504214/ef664b42-b00b-11e6-8682-ca6f2adee2c6.png">

<img width="1004" alt="screen shot 2016-11-21 at 5 00 02 pm" src="https://cloud.githubusercontent.com/assets/406251/20504226/fbf4ae9e-b00b-11e6-8ed7-f7b906f1655b.png">

**Comment by ChristineXYS** [comment]
Find the related ticket in AFNetworking. https://github.com/AFNetworking/AFNetworking/issues/2523. 

Fix this by avoiding re-creating SHAFHTTPRequestSerializer.

**Comment by ChristineXYS** [comment]
Fixed in release 1.8.6.
